// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Adjust the confidence threshold for facial recognition.
 *
 * - adjustConfidenceThreshold - A function that adjusts the confidence threshold for facial recognition.
 * - AdjustConfidenceThresholdInput - The input type for the adjustConfidenceThreshold function.
 * - AdjustConfidenceThresholdOutput - The return type for the adjustConfidenceThreshold function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AdjustConfidenceThresholdInputSchema = z.object({
  environment: z.string().describe('The environment where facial recognition is used (e.g., office, outdoor).'),
  feedback: z.string().describe('User feedback on current facial recognition accuracy (e.g., too many false positives).'),
});
export type AdjustConfidenceThresholdInput = z.infer<typeof AdjustConfidenceThresholdInputSchema>;

const AdjustConfidenceThresholdOutputSchema = z.object({
  newThreshold: z.number().describe('The new confidence threshold value (0 to 1).'),
  reason: z.string().describe('The reason for adjusting the confidence threshold.'),
});
export type AdjustConfidenceThresholdOutput = z.infer<typeof AdjustConfidenceThresholdOutputSchema>;

export async function adjustConfidenceThreshold(input: AdjustConfidenceThresholdInput): Promise<AdjustConfidenceThresholdOutput> {
  return adjustConfidenceThresholdFlow(input);
}

const prompt = ai.definePrompt({
  name: 'adjustConfidenceThresholdPrompt',
  input: {
    schema: z.object({
      environment: z.string().describe('The environment where facial recognition is used (e.g., office, outdoor).'),
      feedback: z.string().describe('User feedback on current facial recognition accuracy (e.g., too many false positives).'),
    }),
  },
  output: {
    schema: z.object({
      newThreshold: z.number().describe('The new confidence threshold value (0 to 1).'),
      reason: z.string().describe('The reason for adjusting the confidence threshold.'),
    }),
  },
  prompt: `You are an AI assistant that helps to adjust the confidence threshold for facial recognition.

  Given the environment and user feedback, determine the new confidence threshold value.

  Environment: {{{environment}}}
  Feedback: {{{feedback}}}

  Consider the following when determining the new threshold:
  - If there are too many false positives, increase the threshold.
  - If there are too many false negatives, decrease the threshold.
  - The threshold should be between 0 and 1.
  - The reason should explain why the threshold was adjusted.
  `,
});

const adjustConfidenceThresholdFlow = ai.defineFlow<
  typeof AdjustConfidenceThresholdInputSchema,
  typeof AdjustConfidenceThresholdOutputSchema
>(
  {
    name: 'adjustConfidenceThresholdFlow',
    inputSchema: AdjustConfidenceThresholdInputSchema,
    outputSchema: AdjustConfidenceThresholdOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
