// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Enhances the quality of an image using an LLM.
 *
 * - enhanceImageQuality - A function that enhances the image quality.
 * - EnhanceImageQualityInput - The input type for the enhanceImageQuality function.
 * - EnhanceImageQualityOutput - The return type for the enhanceImageQuality function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const EnhanceImageQualityInputSchema = z.object({
  imageUrl: z.string().describe('The URL of the image to enhance.'),
});
export type EnhanceImageQualityInput = z.infer<typeof EnhanceImageQualityInputSchema>;

const EnhanceImageQualityOutputSchema = z.object({
  enhancedImageUrl: z.string().describe('The URL of the enhanced image.'),
  enhancementDetails: z.string().describe('Details about the enhancement process.'),
});
export type EnhanceImageQualityOutput = z.infer<typeof EnhanceImageQualityOutputSchema>;

export async function enhanceImageQuality(input: EnhanceImageQualityInput): Promise<EnhanceImageQualityOutput> {
  return enhanceImageQualityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enhanceImageQualityPrompt',
  input: {
    schema: z.object({
      imageUrl: z.string().describe('The URL of the image to enhance.'),
    }),
  },
  output: {
    schema: z.object({
      enhancedImageUrl: z.string().describe('The URL of the enhanced image.'),
      enhancementDetails: z.string().describe('Details about the enhancement process.'),
    }),
  },
  prompt: `You are an AI image enhancement expert. You will enhance the image quality of the provided image and provide details on what enhancements were made.

Enhance the image at this URL: {{imageUrl}}

Respond with the URL of the enhanced image and details of the enhancement process, including specific techniques used to improve the image quality. Return the URL in enhancedImageUrl and the details in enhancementDetails.`, 
});

const enhanceImageQualityFlow = ai.defineFlow<
  typeof EnhanceImageQualityInputSchema,
  typeof EnhanceImageQualityOutputSchema
>(
  {
    name: 'enhanceImageQualityFlow',
    inputSchema: EnhanceImageQualityInputSchema,
    outputSchema: EnhanceImageQualityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
